### ISSUE TITLE
syntax error when start mydumper

### ISSUE THREAD

**Issue by unclesamwk** [XeLabs/go-mydumper#1]
Hey,

i build mydumper in official golang1.9 docker container with no failures etc.
When ich start mydumper i got an failure:

```root@9bf172ff5e5e:~/go-mydumper# ./bin/mydumper
./bin/mydumper: line 1: syntax error near unexpected token `newline'
./bin/mydumper: line 1: `!<arch>'```

myloader works successfully.

Any idea?

greetings
Sam

**Comment by BohuTANG** [comment]
Hello,

Thank you for reporting the issue.
Fixed with commit 5882e69c053d690b0db4a14d83df2c3b1c373c51, please try again.

**Comment by unclesamwk** [comment]
It works! Thank you

Another question:
It will be useful, build static binaries for 386 and x86/amd64.

I dont now, how it implemented.
restic backup do it very well ...

greetings sam

**Comment by BohuTANG** [comment]
@unclesamwk 

If I understand your question correctly, you're asking the golang's cross compling:
https://golang.org/doc/install/source#environment

**Comment by unclesamwk** [comment]
Yes

**Comment by BohuTANG** [comment]
Ok, the answer is go-mydumper is implemented in purge go :dancer:

**Comment by unclesamwk** [comment]
Can you please explain your answer and what it means ... thx

**Comment by BohuTANG** [comment]
@unclesamwk 

Sorry, I am not familiar with the rules of go compiler, it hard to explain in a sentence or two.
