### ISSUE TITLE
恢复时提示数据库不存在

### ISSUE THREAD

**Issue by dwj999** [XeLabs/go-mydumper#2]
1.备份
mydumper -h xxx -P 3306 -u xxx -p xxx -db epg -o epg_mydumper
2.恢复
myloader -h xxx -P 3306 -u xxx -p xxx -d epg_mydumper
3.报错
日志详情:
 2017/10/12 16:38:02.676001 loader.go:75:         [INFO]        restoring.database[epg]
panic: Unknown database 'pg' (errno 1049) (sqlstate 42000)

goroutine 1 [running]:
panic(0x559300, 0xc42024fb40)
        /usr/lib/golang/src/runtime/panic.go:500 +0x1a1
common.AssertNil(0x630780, 0xc42024fb40)
        /usr/local/mydumper/src/common/common.go:65 +0x5c
common.restoreTableSchema(0xc42007c6d0, 0xc420010280, 0xc420250000, 0x2b, 0x40)
        /usr/local/mydumper/src/common/loader.go:87 +0x200
common.Loader(0xc42007c6d0, 0xc420051ea8)
        /usr/local/mydumper/src/common/loader.go:149 +0x1de
main.main()
        /usr/local/mydumper/src/myloader/main.go:59 +0x1e8
4.其他
备份其他数据库时,再恢复时,同样提示的是当前数据库名第1个字母后的数据库名不存在

**Comment by BohuTANG** [comment]
请确认下epg_mydumper下的*schema-create.sql是否存储以及内容。
在loader成功的时候，会打印一条:
log.Info("restoring.database[%s]", name)

**Comment by dwj999** [comment]
epg-schema-create.sql内容:create database if not exists `epg`;
恢复时,打印的前2行是:
2017/10/12 16:38:02.676001 loader.go:75: [INFO] restoring.database[epg]
panic: Unknown database 'pg' (errno 1049) (sqlstate 42000)

**Comment by BohuTANG** [comment]
@dwj999 

请确认下数据库是epg还是pg？
这个错误看起来是pg下的表，请:
show databases;

然后ls epg_mydumper看看

**Comment by dwj999** [comment]
[link](http://note.youdao.com/yws/public/resource/e0ba2e3401841ebd1de153dcd17660b7/xmlnote/8685A232952C4C79A2EC2AFEA561202F/38142)
[link](http://note.youdao.com/yws/public/resource/e0ba2e3401841ebd1de153dcd17660b7/xmlnote/018BEFF21A30421E895A872B2176D698/38143)
数据库的版本切了几个,其中也包括RDS

**Comment by dwj999** [comment]
![11111](https://user-images.githubusercontent.com/11435208/31596825-875b2dd2-b277-11e7-86ba-94f67eb108e8.png)
![22222](https://user-images.githubusercontent.com/11435208/31596826-878aad00-b277-11e7-81af-23344060d2ac.png)
数据库的版本切换了几个,其中也包括RDS,数据库名字也换了几个,效果是一样,还是报错.

**Comment by BohuTANG** [comment]
@dwj999 

已经修复，请获取最新版本试试．
commit:
https://github.com/XeLabs/go-mydumper/commit/a733e688359f04840903d643f823d60843ee98d2

**Comment by dwj999** [comment]
@BohuTANG 感谢,已经修复,可正常备份恢复.

**Comment by BohuTANG** [comment]
@dwj999 

多谢发现问题并提交！
