### ISSUE TITLE
[bug] on mysql 5.7

### ISSUE THREAD

**Issue by yiwenshuo** [xelabs/go-mydumper#20]
When I use command :
./myloader -h 127.0.0.1  -P 3306 -u root -p Root@123 -d       okash_loan_apply
after imort data after minutes later,but got error

`main.main()
        /root/go-mydumper/src/myloader/main.go:62 +0x260
panic: Access denied for user 'root'@'127.0.0.1' (using password: YES) (errno 1045) (sqlstate 28000)

goroutine 1 [running]:
common.AssertNil(...)
        /root/go-mydumper/src/common/common.go:75
common.Loader(0xc00004a5b0, 0xc0000b3e90)
        /root/go-mydumper/src/common/loader.go:154 +0x860
main.main()
        /root/go-mydumper/src/myloader/main.go:62 +0x260
panic: Access denied for user 'root'@'127.0.0.1' (using password: YES) (errno 1045) (sqlstate 28000)

goroutine 1 [running]:
common.AssertNil(...)
        /root/go-mydumper/src/common/common.go:75
common.Loader(0xc00004a5b0, 0xc0000b3e90)
        /root/go-mydumper/src/common/loader.go:154 +0x860
main.main()
        /root/go-mydumper/src/myloader/main.go:62 +0x260
panic: Access denied for user 'root'@'127.0.0.1' (using password: YES) (errno 1045) (sqlstate 28000)

goroutine 1 [running]:
common.AssertNil(...)
        /root/go-mydumper/src/common/common.go:75
common.Loader(0xc0000825a0, 0xc0000cbe90)
        /root/go-mydumper/src/common/loader.go:154 +0x860
main.main()
        /root/go-mydumper/src/myloader/main.go:62 +0x260`

**Comment by BohuTANG** [comment]
@yiwenshuo 

Hi, 
The first, we should make sure that you can connect your MySQL with your user and password what the myloader using.
