### ISSUE TITLE
Does it support where condition?

### ISSUE THREAD

**Issue by jmbkeyes** [xelabs/go-mydumper#25]
for large tables(more than 10 million records), can it only dump records which meets expected condition?

**Comment by BohuTANG** [comment]
See https://github.com/xelabs/go-mydumper/blob/master/conf/mydumper.ini.sample#L20

**Comment by jmbkeyes** [comment]
ok, it supports via read config files.
does it support in shell command directly (e.g. /bin/mydumper -where)?

**Comment by BohuTANG** [comment]
No

**Comment by jmbkeyes** [comment]
It still requires go runtime after making build, right?

**Comment by BohuTANG** [comment]
> It still requires go runtime after making build, right?
After make build, can be run anywhere, it's golang.

**Comment by jmbkeyes** [comment]
Oh, I meens that it can be run on the machine which does not install golang runtime?

**Comment by BohuTANG** [comment]
Yes,  golang is a statically typed, compiled programming language

**Comment by jmbkeyes** [comment]
thanks for quick response.
