### ISSUE TITLE
不能添加外键约束

### ISSUE THREAD

**Issue by dwj999** [XeLabs/go-mydumper#3]
![33333](https://user-images.githubusercontent.com/11435208/31650806-a35964d4-b34b-11e7-8a93-8159dedacc9d.png)
mydumper备份后,myloader恢复时,提示这个错误,恢复中断.

请问恢复时,程序有没有设置FOREIGN_KEY_CHECKS=0呢

**Comment by BohuTANG** [comment]
@dwj999 
目前是没有任何设置的，这个在数据库里自己设置先吧

**Comment by dwj999** [comment]
RDS好像没法设置,自建的数据库倒没问题

**Comment by BohuTANG** [comment]
@dwj999 

那就需要改下dumper出来的DDL了，把foreign key constraint去掉
