### ISSUE TITLE
mystreamer不支持在downstream侧重命名database

### ISSUE THREAD

**Issue by blackghost-01** [XeLabs/go-mydumper#4]

**Comment by blackghost-01** [comment]
这是一个需求，比如我用来做历史数据归档时，可能有相同的库名，希望能够通过定义不同的库名对上游加以区分

**Comment by BohuTANG** [comment]
@blackghost-01 

Thank you for your report.
The next release will support this feature.

**Comment by BohuTANG** [comment]
@blackghost-01 

The master branch have add -2db flag for you.
Usage:
```
./bin/mystreamer -h 192.168.0.2 -P 3306 -u mock -p mock -db sbtest -2h 192.168.0.3 -2P 3306 -2u mock -2p mock -2db tpsbtest
  -2db string
    	Downstream database, default(if NULL) is same as upstream db

```

**Comment by blackghost-01** [comment]
已测，功能ok，但是需要提前建好2db指定的database，是否可以再优化一下，自动创建？

**Comment by BohuTANG** [comment]
@blackghost-01 

Please re-pull the master branch, the commit id: f85096d2015b13fb24810ebccfec63ba8c928160

**Comment by blackghost-01** [comment]
已测试，功能ok，赞响应速度
