### ISSUE TITLE
【feature】mystreamer支持upstream和downstream使用不同的存储引擎

### ISSUE THREAD

**Issue by blackghost-01** [XeLabs/go-mydumper#5]
数据迁移过程中（例如历史数据归档），源库和目标库希望使用不同的存储引擎（比如tokudb或者myrocks），达到数据压缩等目的。所以就需要在导入时，支持指定存储引擎类型，或者导出时忽略存储引擎选项（目标库有设置选定的默认存储引擎）

**Comment by BohuTANG** [comment]
Hi @blackghost-01 ,

From the mystreamer side, we should to parse the table schema and change the ENGINE option to TokuDB/MyRocks or others, so we think this issue priority is lower.

As you said, we can do that by setting the default engine.
Thanks.

**Comment by blackghost-01** [comment]
期待实现

**Comment by BohuTANG** [comment]
@blackghost-01 

This feature is done, the commit id is here:
https://github.com/XeLabs/go-mydumper/commit/a0ee86efcbf1a7e2a3804c90c0370c188892a06f

Now, we can use the flage '--2engine=tokudb' to replace the upstream engine.
```
  -2engine string
    	Downstream table engine
```

**Comment by blackghost-01** [comment]
great job
