### ISSUE TITLE
myloader don't run and don't show error

### ISSUE THREAD

**Issue by silasrm** [xelabs/go-mydumper#8]
Hi,

I'm trying to using myloader locally, and I use the password of root user as empty. Running this:

> ~/tmp/go-mydumper/bin/myloader -h localhost -P 3306 -u root -d dumper2 

Return this, without any message to explain don't execute the restoring:

> Usage: /home/silasrm/tmp/go-mydumper/bin/myloader -h [HOST] -P [PORT] -u [USER] -p [PASSWORD] -d [DIR] [-o]
>   -P int
>     	TCP/IP port to connect to (default 3306)
>   -d string
>     	Directory of the dump to import
>   -h string
>     	The host to connect to
>   -o	Drop tables if they already exist
>   -p string
>     	User password
>   -t int
>     	Number of threads to use (default 16)
>   -u string
>     	Username with privileges to run the loader

Any idea I'm wrong?

**Comment by silasrm** [comment]
dumper2 is a folder with go-mydumper/mydumper files.

**Comment by BohuTANG** [comment]
Hello,

The password can't be empty, you should create a new user with password and try again.

**Comment by BohuTANG** [comment]
Or,

Re-pull the  source from https://github.com/xelabs/go-mydumper
The empty password issue fixed on the commit:
https://github.com/xelabs/go-mydumper/commit/4f4b271664d342bdf097bd7e8948cdac1d376e6d

**Comment by silasrm** [comment]
Hi,

I see the code and edit. Removing this passoword empty check and add this sql to disabled foreign constraint check:

```
err = conn.Execute("SET FOREIGN_KEY_CHECKS=0")
    AssertNil(err)
```

Add after call of use database;

**Comment by silasrm** [comment]
https://github.com/xelabs/go-mydumper/pull/9
